### ISSUE TITLE
v5.0 won't start with clean install

### ISSUE THREAD

**Issue by brianegge** [mlapaglia/OpenAlprWebhookProcessor#111]
```
dotnet ./OpenAlprWebhookProcessor.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenAlprWebhookProcessor.Hydrator.HydrationService.ScheduleHydrationAsync(CancellationToken cancellationToken) in /home/runner/work/OpenAlprWebhookProcessor/OpenAlprWebhookProcessor/OpenAlprWebhookProcessor/Hydration/HydrationService.cs:line 71
   at OpenAlprWebhookProcessor.Hydrator.HydrationService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/OpenAlprWebhookProcessor/OpenAlprWebhookProcessor/OpenAlprWebhookProcessor/Hydration/HydrationService.cs:line 52
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at OpenAlprWebhookProcessor.Program.Main(String[] args) in /home/runner/work/OpenAlprWebhookProcessor/OpenAlprWebhookProcessor/OpenAlprWebhookProcessor/Program.cs:line 15
```

docker
```
2024-01-28 07:19:48 Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
2024-01-28 07:19:48    at OpenAlprWebhookProcessor.Hydrator.HydrationService.ScheduleHydrationAsync(CancellationToken cancellationToken) in /src/OpenAlprWebhookProcessor/Hydration/HydrationService.cs:line 71
2024-01-28 07:19:48    at OpenAlprWebhookProcessor.Hydrator.HydrationService.StartAsync(CancellationToken cancellationToken) in /src/OpenAlprWebhookProcessor/Hydration/HydrationService.cs:line 52
2024-01-28 07:19:48    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2024-01-28 07:19:48    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2024-01-28 07:19:48    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2024-01-28 07:19:48    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2024-01-28 07:19:48    at OpenAlprWebhookProcessor.Program.Main(String[] args) in /src/OpenAlprWebhookProcessor/Program.cs:line 15
```

**Comment by brianegge** [comment]
v5.1.0-alpha25 works, v5.1.0-alpha26 is broken.
```
docker run -it -p 3859:80 -v C:\LPR\:/app/config/ mlapaglia/openalprwebhookprocessor:v5.1.0-alpha26
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenAlprWebhookProcessor.Hydrator.HydrationService.ScheduleHydrationAsync(CancellationToken cancellationToken) in /src/OpenAlprWebhookProcessor/Hydration/HydrationService.cs:line 71
   at OpenAlprWebhookProcessor.Hydrator.HydrationService.StartAsync(CancellationToken cancellationToken) in /src/OpenAlprWebhookProcessor/Hydration/HydrationService.cs:line 52
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at OpenAlprWebhookProcessor.Program.Main(String[] args) in /src/OpenAlprWebhookProcessor/Program.cs:line 15
```

**Comment by mlapaglia** [comment]
should be fixed in latest. generally don't use the alpha builds unless you've got your data backed up, stick to `latest` or any of the main release versions: https://github.com/mlapaglia/OpenAlprWebhookProcessor/releases

**Comment by brianegge** [comment]
Working great - thank you very much. I changed the port to 8080 after reading the release notes.
